### ISSUE TITLE
How do you get the full file path while using the file picker on MacOS?

### ISSUE THREAD

**Issue by sano-apps** [datvm/LukeMauiFilePicker#1]
var file = await picker.PickFileAsync("Select a file", FileType);

file.FileResult.FullPath is always null
file.FileName is not the full path

**Comment by datvm** [comment]
Hi,

You are right I didn't think about that when making this. Unfortunately I am no longer active in MAUI development for now. Can you make a PR? The code that you need to add should be here:

https://github.com/datvm/LukeMauiFilePicker/blob/6ad55eab9f60827f07e80093c166c2d37621baf4/LukeMauiFilePicker/FilePickerService.MaciOS.cs#L78C30-L78C30

**Comment by brightertools** [comment]
I have the same issue, the Filename at the top level is set, but FileResult is null so cannot get the path.

I found this as the workaround to the community tools one, but will obviously need the full path to use the actual path?

..saw the PayPal link, but I guess its not supported anymore, so I guess a contribution wont help, I will try look at the code..

**Comment by brightertools** [comment]
I forked this repo and fixed this for MacOS,

Forked version here: https://github.com/brightertools/MauiFilePicker, with link to a new nuget package..

**Comment by brightertools** [comment]
I forked the repro, and created my own nuget changing various bits, I have gone back to try and do a pull request, but didn't realise those are done on forks? I cannot create another fork and cannot submit a pull request for a single file, so will need to have time to undo all that.. in the meantime, the fix is just 1 line of code in the file that @datvm mentioned.

**Comment by brightertools** [comment]
> @brightertools yes you can create a pull request so I can merge it into this repository. You perform it from your own fork/repo (https://github.com/brightertools/MauiFilePicker). Simply go to the [PR tab of your fork](https://github.com/brightertools/MauiFilePicker/pulls) and click New pull request. [The official documentation is here](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests).
> 
> EDIT: I see you changed many other files. If you don't mind, I will manually copy the relevant changes into this repo and add a credit in README and code comment but the Github commit will be under my name.
> 
> > ..saw the PayPal link, but I guess its not supported anymore, so I guess a contribution wont help, I will try look at the code..
> 
> You are right, I am not actively code MAUI anymore because my job moved to another stack. I can still check and build any fixes contributed by anyone though :)

Hi,

no problem, glad it helped. 👍

**Comment by datvm** [comment]
This should fixed in the latest version 1.1
